name: CI - Docker Build & Trivy Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docker-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t demo-secure:latest .

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          format: json
          output: trivy-report.json
          scan-type: image
          image-ref: demo-secure:latest

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
